const elements = {
    1: { number: 1, symbol: 'H', name: 'Hydrogen', mass: 1.008, category: 'Nonmetal', row: 1, col: 1 },
    2: { number: 2, symbol: 'He', name: 'Helium', mass: 4.003, category: 'Noble Gas', row: 1, col: 18 },
    3: { number: 3, symbol: 'Li', name: 'Lithium', mass: 6.941, category: 'Alkali Metal', row: 2, col: 1 },
    4: { number: 4, symbol: 'Be', name: 'Beryllium', mass: 9.012, category: 'Alkaline Earth Metal', row: 2, col: 2 },
    5: { number: 5, symbol: 'B', name: 'Boron', mass: 10.811, category: 'Metalloid', row: 2, col: 13 },
    6: { number: 6, symbol: 'C', name: 'Carbon', mass: 12.011, category: 'Nonmetal', row: 2, col: 14 },
    7: { number: 7, symbol: 'N', name: 'Nitrogen', mass: 14.007, category: 'Nonmetal', row: 2, col: 15 },
    8: { number: 8, symbol: 'O', name: 'Oxygen', mass: 15.999, category: 'Nonmetal', row: 2, col: 16 },
    9: { number: 9, symbol: 'F', name: 'Fluorine', mass: 18.998, category: 'Halogen', row: 2, col: 17 },
    10: { number: 10, symbol: 'Ne', name: 'Neon', mass: 20.180, category: 'Noble Gas', row: 2, col: 18 },
    11: { number: 11, symbol: 'Na', name: 'Sodium', mass: 22.990, category: 'Alkali Metal', row: 3, col: 1 },
    12: { number: 12, symbol: 'Mg', name: 'Magnesium', mass: 24.305, category: 'Alkaline Earth Metal', row: 3, col: 2 },
    13: { number: 13, symbol: 'Al', name: 'Aluminum', mass: 26.982, category: 'Post-transition Metal', row: 3, col: 13 },
    14: { number: 14, symbol: 'Si', name: 'Silicon', mass: 28.086, category: 'Metalloid', row: 3, col: 14 },
    15: { number: 15, symbol: 'P', name: 'Phosphorus', mass: 30.974, category: 'Nonmetal', row: 3, col: 15 },
    16: { number: 16, symbol: 'S', name: 'Sulfur', mass: 32.065, category: 'Nonmetal', row: 3, col: 16 },
    17: { number: 17, symbol: 'Cl', name: 'Chlorine', mass: 35.453, category: 'Halogen', row: 3, col: 17 },
    18: { number: 18, symbol: 'Ar', name: 'Argon', mass: 39.948, category: 'Noble Gas', row: 3, col: 18 },
    19: { number: 19, symbol: 'K', name: 'Potassium', mass: 39.098, category: 'Alkali Metal', row: 4, col: 1 },
    20: { number: 20, symbol: 'Ca', name: 'Calcium', mass: 40.078, category: 'Alkaline Earth Metal', row: 4, col: 2 },
     21: { number: 21, symbol: 'Sc', name: 'Scandium', mass: 44.956, category: 'Transition Metal', row: 4, col: 3 },
    22: { number: 22, symbol: 'Ti', name: 'Titanium', mass: 47.867, category: 'Transition Metal', row: 4, col: 4 },
    23: { number: 23, symbol: 'V', name: 'Vanadium', mass: 50.942, category: 'Transition Metal', row: 4, col: 5 },
    24: { number: 24, symbol: 'Cr', name: 'Chromium', mass: 51.996, category: 'Transition Metal', row: 4, col: 6 },
    25: { number: 25, symbol: 'Mn', name: 'Manganese', mass: 54.938, category: 'Transition Metal', row: 4, col: 7 },
    26: { number: 26, symbol: 'Fe', name: 'Iron', mass: 55.845, category: 'Transition Metal', row: 4, col: 8 },
    27: { number: 27, symbol: 'Co', name: 'Cobalt', mass: 58.933, category: 'Transition Metal', row: 4, col: 9 },
    28: { number: 28, symbol: 'Ni', name: 'Nickel', mass: 58.693, category: 'Transition Metal', row: 4, col: 10 },
    29: { number: 29, symbol: 'Cu', name: 'Copper', mass: 63.546, category: 'Transition Metal', row: 4, col: 11 },
    30: { number: 30, symbol: 'Zn', name: 'Zinc', mass: 65.38, category: 'Transition Metal', row: 4, col: 12 },
     31: { number: 31, symbol: 'Ga', name: 'Gallium', mass: 69.723, category: 'Post-transition Metal', row: 4, col: 13 },
    32: { number: 32, symbol: 'Ge', name: 'Germanium', mass: 72.630, category: 'Metalloid', row: 4, col: 14 },
    33: { number: 33, symbol: 'As', name: 'Arsenic', mass: 74.922, category: 'Metalloid', row: 4, col: 15 },
    34: { number: 34, symbol: 'Se', name: 'Selenium', mass: 78.971, category: 'Nonmetal', row: 4, col: 16 },
    35: { number: 35, symbol: 'Br', name: 'Bromine', mass: 79.904, category: 'Halogen', row: 4, col: 17 },
     36: { number: 36, symbol: 'Kr', name: 'Krypton', mass: 83.798, category: 'Noble Gas', row: 4, col: 18 },
    37: { number: 37, symbol: 'Rb', name: 'Rubidium', mass: 85.468, category: 'Alkali Metal', row: 5, col: 1 },
    38: { number: 38, symbol: 'Sr', name: 'Strontium', mass: 87.62, category: 'Alkaline Earth Metal', row: 5, col: 2 },
    39: { number: 39, symbol: 'Y', name: 'Yttrium', mass: 88.906, category: 'Transition Metal', row: 5, col: 3 },
    40: { number: 40, symbol: 'Zr', name: 'Zirconium', mass: 91.224, category: 'Transition Metal', row: 5, col: 4 },
    41: { number: 41, symbol: 'Nb', name: 'Niobium', mass: 92.906, category: 'Transition Metal', row: 5, col: 5 },
    42: { number: 42, symbol: 'Mo', name: 'Molybdenum', mass: 95.95, category: 'Transition Metal', row: 5, col: 6 },
    43: { number: 43, symbol: 'Tc', name: 'Technetium', mass: 98, category: 'Transition Metal', row: 5, col: 7 },
    44: { number: 44, symbol: 'Ru', name: 'Ruthenium', mass: 101.07, category: 'Transition Metal', row: 5, col: 8 },
    45: { number: 45, symbol: 'Rh', name: 'Rhodium', mass: 102.91, category: 'Transition Metal', row: 5, col: 9 },
    46: { number: 46, symbol: 'Pd', name: 'Palladium', mass: 106.42, category: 'Transition Metal', row: 5, col: 10 },
    47: { number: 47, symbol: 'Ag', name: 'Silver', mass: 107.87, category: 'Transition Metal', row: 5, col: 11 },
    48: { number: 48, symbol: 'Cd', name: 'Cadmium', mass: 112.41, category: 'Transition Metal', row: 5, col: 12 },
    49: { number: 49, symbol: 'In', name: 'Indium', mass: 114.82, category: 'Post-transition Metal', row: 5, col: 13 },
    50: { number: 50, symbol: 'Sn', name: 'Tin', mass: 118.71, category: 'Post-transition Metal', row: 5, col: 14 },
    51: { number: 51, symbol: 'Sb', name: 'Antimony', mass: 121.76, category: 'Metalloid', row: 5, col: 15 },
    52: { number: 52, symbol: 'Te', name: 'Tellurium', mass: 127.60, category: 'Metalloid', row: 5, col: 16 },
    53: { number: 53, symbol: 'I', name: 'Iodine', mass: 126.90, category: 'Halogen', row: 5, col: 17 },
    54: { number: 54, symbol: 'Xe', name: 'Xenon', mass: 131.29, category: 'Noble Gas', row: 5, col: 18 },
    55: { number: 55, symbol: 'Cs', name: 'Cesium', mass: 132.91, category: 'Alkali Metal', row: 6, col: 1 },
    56: { number: 56, symbol: 'Ba', name: 'Barium', mass: 137.33, category: 'Alkaline Earth Metal', row: 6, col: 2 },
    57: { number: 57, symbol: 'La', name: 'Lanthanum', mass: 138.91, category: 'Lanthanide', row: 8, col: 3 },
    58: { number: 58, symbol: 'Ce', name: 'Cerium', mass: 140.12, category: 'Lanthanide', row: 8, col: 4 },
    59: { number: 59, symbol: 'Pr', name: 'Praseodymium', mass: 140.91, category: 'Lanthanide', row: 8, col: 5 },
    60: { number: 60, symbol: 'Nd', name: 'Neodymium', mass: 144.24, category: 'Lanthanide', row: 8, col: 6 },
    61: { number: 61, symbol: 'Pm', name: 'Promethium', mass: 145, category: 'Lanthanide', row: 8, col: 7 },
    62: { number: 62, symbol: 'Sm', name: 'Samarium', mass: 150.36, category: 'Lanthanide', row: 8, col: 8 },
    63: { number: 63, symbol: 'Eu', name: 'Europium', mass: 151.96, category: 'Lanthanide', row: 8, col: 9 },
    64: { number: 64, symbol: 'Gd', name: 'Gadolinium', mass: 157.25, category: 'Lanthanide', row: 8, col: 10 },
    65: { number: 65, symbol: 'Tb', name: 'Terbium', mass: 158.93, category: 'Lanthanide', row: 8, col: 11 },
    66: { number: 66, symbol: 'Dy', name: 'Dysprosium', mass: 162.50, category: 'Lanthanide', row: 8, col: 12 },
    67: { number: 67, symbol: 'Ho', name: 'Holmium', mass: 164.93, category: 'Lanthanide', row: 8, col: 13 },
    68: { number: 68, symbol: 'Er', name: 'Erbium', mass: 167.26, category: 'Lanthanide', row: 8, col: 14 },
    69: { number: 69, symbol: 'Tm', name: 'Thulium', mass: 168.93, category: 'Lanthanide', row: 8, col: 15 },
    70: { number: 70, symbol: 'Yb', name: 'Ytterbium', mass: 173.05, category: 'Lanthanide', row: 8, col: 16 },
    71: { number: 71, symbol: 'Lu', name: 'Lutetium', mass: 174.97, category: 'Lanthanide', row: 8, col: 17 },
    72: { number: 72, symbol: 'Hf', name: 'Hafnium', mass: 178.49, category: 'Transition Metal', row: 6, col: 4 },
    73: { number: 73, symbol: 'Ta', name: 'Tantalum', mass: 180.95, category: 'Transition Metal', row: 6, col: 5 },
    74: { number: 74, symbol: 'W', name: 'Tungsten', mass: 183.84, category: 'Transition Metal', row: 6, col: 6 },
    75: { number: 75, symbol: 'Re', name: 'Rhenium', mass: 186.21, category: 'Transition Metal', row: 6, col: 7 },