const elements = {
    1: { number: 1, symbol: 'H', name: 'Hydrogen', mass: 1.008, category: 'Nonmetal', row: 1, col: 1 },
    2: { number: 2, symbol: 'He', name: 'Helium', mass: 4.003, category: 'Noble Gas', row: 1, col: 18 },
    3: { number: 3, symbol: 'Li', name: 'Lithium', mass: 6.941, category: 'Alkali Metal', row: 2, col: 1 },
    4: { number: 4, symbol: 'Be', name: 'Beryllium', mass: 9.012, category: 'Alkaline Earth Metal', row: 2, col: 2 },
    5: { number: 5, symbol: 'B', name: 'Boron', mass: 10.811, category: 'Metalloid', row: 2, col: 13 },
    6: { number: 6, symbol: 'C', name: 'Carbon', mass: 12.011, category: 'Nonmetal', row: 2, col: 14 },
    7: { number: 7, symbol: 'N', name: 'Nitrogen', mass: 14.007, category: 'Nonmetal', row: 2, col: 15 },
    8: { number: 8, symbol: 'O', name: 'Oxygen', mass: 15.999, category: 'Nonmetal', row: 2, col: 16 },
    9: { number: 9, symbol: 'F', name: 'Fluorine', mass: 18.998, category: 'Halogen', row: 2, col: 17 },
    10: { number: 10, symbol: 'Ne', name: 'Neon', mass: 20.180, category: 'Noble Gas', row: 2, col: 18 },
    11: { number: 11, symbol: 'Na', name: 'Sodium', mass: 22.990, category: 'Alkali Metal', row: 3, col: 1 },
    12: { number: 12, symbol: 'Mg', name: 'Magnesium', mass: 24.305, category: 'Alkaline Earth Metal', row: 3, col: 2 },
    13: { number: 13, symbol: 'Al', name: 'Aluminum', mass: 26.982, category: 'Post-transition Metal', row: 3, col: 13 },
    14: { number: 14, symbol: 'Si', name: 'Silicon', mass: 28.086, category: 'Metalloid', row: 3, col: 14 },
    15: { number: 15, symbol: 'P', name: 'Phosphorus', mass: 30.974, category: 'Nonmetal', row: 3, col: 15 },
    16: { number: 16, symbol: 'S', name: 'Sulfur', mass: 32.065, category: 'Nonmetal', row: 3, col: 16 },
    17: { number: 17, symbol: 'Cl', name: 'Chlorine', mass: 35.453, category: 'Halogen', row: 3, col: 17 },
    18: { number: 18, symbol: 'Ar', name: 'Argon', mass: 39.948, category: 'Noble Gas', row: 3, col: 18 },
    19: { number: 19, symbol: 'K', name: 'Potassium', mass: 39.098, category: 'Alkali Metal', row: 4, col: 1 },
    20: { number: 20, symbol: 'Ca', name: 'Calcium', mass: 40.078, category: 'Alkaline Earth Metal', row: 4, col: 2 },
     21: { number: 21, symbol: 'Sc', name: 'Scandium', mass: 44.956, category: 'Transition Metal', row: 4, col: 3 },
    22: { number: 22, symbol: 'Ti', name: 'Titanium', mass: 47.867, category: 'Transition Metal', row: 4, col: 4 },
    23: { number: 23, symbol: 'V', name: 'Vanadium', mass: 50.942, category: 'Transition Metal', row: 4, col: 5 },
    24: { number: 24, symbol: 'Cr', name: 'Chromium', mass: 51.996, category: 'Transition Metal', row: 4, col: 6 },
    25: { number: 25, symbol: 'Mn', name: 'Manganese', mass: 54.938, category: 'Transition Metal', row: 4, col: 7 },
    26: { number: 26, symbol: 'Fe', name: 'Iron', mass: 55.845, category: 'Transition Metal', row: 4, col: 8 },
    27: { number: 27, symbol: 'Co', name: 'Cobalt', mass: 58.933, category: 'Transition Metal', row: 4, col: 9 },
    28: { number: 28, symbol: 'Ni', name: 'Nickel', mass: 58.693, category: 'Transition Metal', row: 4, col: 10 },
    29: { number: 29, symbol: 'Cu', name: 'Copper', mass: 63.546, category: 'Transition Metal', row: 4, col: 11 },
    30: { number: 30, symbol: 'Zn', name: 'Zinc', mass: 65.38, category: 'Transition Metal', row: 4, col: 12 },
     31: { number: 31, symbol: 'Ga', name: 'Gallium', mass: 69.723, category: 'Post-transition Metal', row: 4, col: 13 },
    32: { number: 32, symbol: 'Ge', name: 'Germanium', mass: 72.630, category: 'Metalloid', row: 4, col: 14 },
    33: { number: 33, symbol: 'As', name: 'Arsenic', mass: 74.922, category: 'Metalloid', row: 4, col: 15 },
    34: { number: 34, symbol: 'Se', name: 'Selenium', mass: 78.971, category: 'Nonmetal', row: 4, col: 16 },
    35: { number: 35, symbol: 'Br', name: 'Bromine', mass: 79.904, category: 'Halogen', row: 4, col: 17 },